### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Rudloff** [GEANT/CAT-Android#23]
Hello,

I'm getting an error when trying to build v1.2.7 with Gradle:
```
Execution failed for task ':mergeDebugResources'.
> /home/pierre/www/CAT-Android/res/menu/selectFile.xml: Error: 'F' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore
```

Renaming the file to `selectfile.xml` seems to fix the issue.

**Comment by restena-sw** [comment]
I almost couldn't believe that the capitalisation in a file is relevant these days, but yes, selectFile.xml should be selectfile.xml instead, and this requirement (no capitals) is actually there in the Android API description.

1.2.8 doesn't fix that yet. It should be fixed in the next maintenance version to allow our inclusion into the F-Droid repo.

**Comment by GarethAyres** [comment]
Hello, the file name in the current release is now selectfile.xml so this should be resolved.

**Comment by Rudloff** [comment]
I still see `selectFile.xml` on master, am I missing something?

**Comment by pikachuprof** [comment]
@GarethAyres hey did you forget to push your changes? as @Rudloff pointed the wrong filename is still there...

**Comment by GarethAyres** [comment]
Hello,

I changed it locally, and pushed it, but for some reason this wasnt reflected on GitHub. So i have manually changed the file name now.

Gareth

**Comment by Rudloff** [comment]
It now builds correctly, thanks!

**Comment by pikachuprof** [comment]
playin' a little bit carrier pidgeon @GarethAyres a new release-tag for this fix is needed to go on

https://gitlab.com/fdroid/rfp/issues/796
